{-
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. -}


-- Definition of fibonnacci sequence
fibs = 1:2: zipWith (+) fibs (tail fibs)
{- ghci> take 10 fibs
[1,2,3,5,8,13,21,34,55,89] -}

-- Four Million
fourmil = 4 * 10^6

main = print $ sum [x | x <- takeWhile (< fourmil) fibs, mod x 2 == 0]
